# yamllint disable rule:document-start
{{- if .Values.app.persistence.enabled }}
{{- if not .Values.app.persistence.existingClaim.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wger-media
  {{- with .Values.app.persistence.annotations }}
  annotations:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote}}
  {{- end }}
  {{- end }}
spec:
  accessModes:
  {{- range .Values.app.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.app.persistence.size | quote }}
  {{- if .Values.app.persistence.storageClass }}
  storageClassName:  {{ .Values.app.persistence.storageClass | quote }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wger-static
  {{- with .Values.app.persistence.annotations }}
  annotations:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote}}
  {{- end }}
  {{- end }}
spec:
  accessModes:
  {{- range .Values.app.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.app.persistence.size | quote }}
  {{- if .Values.app.persistence.storageClass }}
  storageClassName:  {{ .Values.app.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
{{- end }}
