---
apiVersion: v2
version: 0.1.3
appVersion: 2.1.0
name: wger
description: A Helm chart for Wger installation on Kubernetes
type: application
maintainers:
  - name: rolandgeider
    email: roland@geider.net
dependencies:
  - name: postgres
    condition: postgres.enabled
    tags:
      - groundhog2k
    version: 0.4.1
    repository: https://groundhog2k.github.io/helm-charts
  - name: redis
    condition: redis.enabled
    tags:
      - groundhog2k
    version: 0.6.0
    repository: https://groundhog2k.github.io/helm-charts
