---
# App settings
app:
  global:
    image: wger/server:latest
    imagePullPolicy: Always
    annotations: {}
    replicas: 1
  persistence:
    enabled: false
    storageClass: null
    accessModes:
      - ReadWriteMany
    size: 8Gi
    annotations: {}
    existingClaim:
      enabled: false
      media: null
      static: null
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  environment:
    - name: TIME_ZONE
      value: UTC
    - name: ENABLE_EMAIL
      value: "False"
    - name: EMAIL_BACKEND
      value: "django.core.mail.backends.console.EmailBackend"
    - name: EMAIL_HOST
      value: None
    - name: EMAIL_PORT
      value: 587
    - name: EMAIL_HOST_USER
      value: None
    - name: EMAIL_HOST_PASSWORD
      value: None
    - name: FROM_EMAIL
      value: test@test.com

ingress:
  enabled: false
  url: fit.example.com
  tls: true
  annotations: {}

service:
  annotations: {}
  type: ClusterIP
  port: 8000

# PostgreSQL Settings for groundhog2k chart. Only a minimum has been specified below.
# For more options, see https://github.com/groundhog2k/helm-charts/tree/master/charts/postgres
postgres:
  # Note: keep these variables present as the chart uses them for the Deployment
  enabled: true
  settings:
    superuser: wger
    superuserPassword: wger
  userDatabase:
    name: wger
  service:
    port: 5432
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ## Storage parameters
  storage:
    ##  Set persistentVolumenClaimName to reference an existing PVC
    persistentVolumeClaimName:
    ## Alternative set requestedSize to define a size for a dynmaically created PVC
    requestedSize: 8Gi
    ## the storage class name
    className:

# Redis Settings for groundhog2k chart. Only a minimum has been specified below.
# For more options, see https://github.com/groundhog2k/helm-charts/tree/master/charts/redis
redis:
  # Note: keep these variables present as the chart uses them for the Deployment
  enabled: true
  auth:
    enabled: false
    password: wger
  storage:
    ##  Set persistentVolumenClaimName to reference an existing PVC
    persistentVolumeClaimName:
    ## Alternative set requestedSize to define a size for a dynmaically created PVC
    ## five times (5x) the amount of memory (RAM)
    requestedSize: 10Gi
    ## the storage class name
    className:

  # For later when redis password in wger is implemented
  # enable .Values.redis.auth.enabled and set the following
  # env and arg
  #
  ## Additional environment variables
  # env:
  #   - name: REDIS_PASSWORD
  #     valueFrom:
  #       secretKeyRef:
  #         name: redis
  #         key: redis-password
  ## Arguments for the container entrypoint process
  # args:
  #   - "--requirepass $(REDIS_PASSWORD)"
